const page = document.body.dataset.page || '';
const links = [
  ['Home', 'index.html', 'home'], ['Services', 'services.html', 'services'], ['Diagnostics', 'diagnostics.html', 'diagnostics', 'hmd'], ['About', 'about.html', 'about', 'hmd'], ['Our Team', 'team.html', 'team'], ['Stories', 'testimonials.html', 'stories', 'hmd'], ['Contact', 'contact.html', 'contact']
];
const navLinks = links.map(([label, href, key, optional]) => `<a class="${page === key ? 'active ' : ''}${optional || ''}" href="${href}">${label}</a>`).join('');
const brand = `<a class="logo" href="index.html" aria-label="KingVet Animal Clinic home"><span class="crown">♛</span><span><span class="king">KING</span><span class="vet">VET</span><small>ANIMAL CLINIC</small></span></a>`;
document.querySelector('[data-site-header]').innerHTML = `<div class="topbar"><div class="container inside"><span>🐾 Your pet's health, our crown priority.</span><span><strong>Open 24/7</strong> · <a href="tel:+639661461766">0966 146 1766</a></span></div></div><header class="site-header"><div class="container nav-row">${brand}<button class="menu" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nav" aria-label="Main navigation">${navLinks}<a class="button" href="appointment.html">Book a visit →</a></nav></div></header>`;
document.querySelector('[data-site-footer]').innerHTML = `<footer class="footer"><div class="container footer-grid"><div>${brand}<p class="footer-copy">Modern, compassionate care for every pet and every pet parent in Quezon City.</p></div><div><h2 class="footer-title">Explore</h2><nav class="footer-links"><a href="services.html">Veterinary services</a><a href="diagnostics.html">Laboratory &amp; diagnostics</a><a href="about.html">About KingVet</a><a href="team.html">Meet our team</a></nav></div><div><h2 class="footer-title">For pet parents</h2><nav class="footer-links"><a href="testimonials.html">Client stories</a><a href="appointment.html">Book an appointment</a><a href="contact.html">Contact &amp; location</a><a href="contact.html#hours">Clinic hours</a></nav></div><div><h2 class="footer-title">Visit or call</h2><div class="footer-contact"><p>Roosevelt Avenue<br>Quezon City, Philippines</p><p><a href="tel:+639661461766">0966 146 1766</a><br><a href="mailto:kingvetanimalclinic@gmail.com">kingvetanimalclinic@gmail.com</a></p></div></div></div><div class="container footer-bottom"><span>© 2026 KingVet Animal Clinic</span><span>Website concept — details to verify before launch</span></div></footer><div class="mobile-cta"><a class="button" href="appointment.html">Book a visit →</a></div>`;
const menu = document.querySelector('.menu'); const nav = document.querySelector('.nav');
if (menu) menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', String(open)); menu.setAttribute('aria-label', open ? 'Close navigation' : 'Open navigation'); });
document.querySelectorAll('[data-demo-form]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const button = form.querySelector('button'); const label = button.textContent; button.textContent = 'Request received — demo only'; button.disabled = true; setTimeout(() => { button.textContent = label; button.disabled = false; }, 3500); }));
